all:
	gcc a.c -o a
	gcc b.c -o b 
	gcc c.c -o c
	gcc d.c -o d
	gcc e.c -o e
	gcc f.c -o f
	gcc g.c -o g
	gcc h.c -o h
	gcc i.c -o i
	gcc j.c -o j -lm
	gcc k.c -o k -lm
	gcc l.c -o l
	gcc m.c -o m
	gcc n.c -o n
clean:
	rm -rf a b c d e f g h i j k l m n