all:
	gcc a.c -o a
	gcc b.c -o b
	gcc c.c -o c
	gcc d.c -o d
	gcc e.c -o e
	gcc f.c -o f
	gcc g.c -o g -lm
	gcc h.c -o h -lm
	gcc i.c -o i -lm
	gcc j.c -o j
	gcc k.c -o k
	gcc l.c -o l
	gcc m.c -o m
clean:
	rm -rf a b c d e f g h i j k l m