all:
	gcc a.c -o a
	gcc b.c -o b -lm
	gcc c.c -o c
	gcc d.c -o d
	gcc e.c -o e
	gcc e2.c -o e2
	gcc f.c -o f
	gcc g.c -o g
	gcc h.c -o h
	gcc i.c -o i
	gcc j.c -o j
	gcc k.c -o k
	gcc l.c -o l
clean:
	rm -rf a b c d e e2 f g h i j k l